#!/bin/bash

set -eu

# applies a basic nftables firewall for a desktop linux pc, installs nftables, enables the service
# allows http,https, dns, dns over tls, ntp and ntpsec, and outbound pings
# meant to be absolutely bare bones, the config is stored in nftables.conf
# edit this file:

#if you edit this var, you may need to edit other nftables scripts
nftables_conf='/etc/nftables.conf'
rules_dir='/etc/nftables'

print_usage(){
  # shellcheck disable=SC2155
  local usage=$(cat << 'HERE' 
  
Usage: sudo ./nftables_desktop ARG1

ARG1 can be:
-i or install - installs nftables
-e or enable - enable firewall
-d or disable - disable firewall
-h or help - prints this help message

HERE
)
  echo "$usage"
}

#check the script runs as root user 
check_run_as_root(){
  if (( EUID != 0 )); then
    echo "This script must be run as root/sudo"
    exit 1
  fi
}

#install firewall
install_firewall(){
  apt-get -yy install nftables  
}

#backup and replace rules with nftables.conf 
enable_firewall(){
  mv "${nftables_conf}" "${nftables_conf}.backup" || true
  cp -pr "nftables.conf" "${nftables_conf}"
  
  mkdir -p "${rules_dir}"
  mkdir -p "${rules_dir}.backup" 
  rm -rf "${rules_dir}.backup"
  mv "${rules_dir}" "${rules_dir}.backup" || true
  rm -rf "${rules_dir}"
  cp -pr "nftables" "${rules_dir}"
  
  nft -f "${nftables_conf}"
  
  systemctl enable nftables.service
  nft list ruleset
}

#flush all rules, disable the nftables service
disable_firewall(){
  nft flush ruleset
  systemctl disable nftables.service
}

#main program counter logic
main(){
  echo "$(basename "$0") started"
  
  case $1 in
    enable|-e|-E)
      check_run_as_root
      enable_firewall
      ;;
    disable|-d|-D)
      check_run_as_root
      disable_firewall
      ;;
    install|-i|-I)
      check_run_as_root
      install_firewall
      ;;
    *)
      print_usage
      ;;
  esac
   
  echo "$(basename "$0") finished"
  exit 0;
}

# Run program
main "${1:-'print usage'}"
